### ISSUE TITLE
erreur à l'installation

### ISSUE THREAD

**Issue by vz777** [roadster31/BestSellers#5]
Bonjour,
après install sur 2.3.4,

```
FatalThrowableError in EventManager.php line 68: 
Fatal error: Undefined class constant 'COL_ID'
```

**Comment by vz777** [comment]
Ce module marche nickel,
il doit inclure des dépendances.
Il est important de jouer à la console, enfin de composer ;)
Peut être prévoir de le mentionner dans le readme.

Merci

**Comment by roadster31** [comment]
Non, ce module n'a aucune dépendance. C'est juste qu'il n'est pas compatible 2.3, à cause de cette constante.

**Comment by vz777** [comment]
Ok je trouvais ça bizzare qu'il en comporte ;) En tout cas, j'ai pu l'installer avec composer.

Merci pour la dernière version, je vais m'occuper de le mettre à jour.
